import './globals.scss'
import { Inter } from 'next/font/google'
import Header from './header/Header'
import Navigator from './navigation/Navigator'
import Player from './components/musicPlayer/Player'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body className={inter.className}>

        <Header />

        <div className='border-none'>
          <Navigator />
          <main className='main'>{children}
           
          </main>
          <div className='player'>
              <Player />
            </div>
        </div>
      </body>
    </html>
  )
}
